export default {
  attendance: 'Attendance',
  attendanceDashboard: 'Dashboard',
  attendanceReports: 'Reports',
  attendanceVisitors: 'Visitors',
  attendanceQrScanner: 'QR Scanner',
  checkIn: 'Check In',
  checkOut: 'Check Out',
  idCards: 'ID Cards',
  incidents: 'Incidents',
  incidentsAlerts: 'Alerts',
  incidentsHealthCases: 'Health Cases',
  incidentsReportingTool: 'Reporting Tool',
  incidentsReports: 'Incident Reports',
  organization: 'Organization',
  organizationBadge: 'Badge Requests',
  organizationParents: 'Parents',
  organizationProfileCompletion: 'Profile Completion',
  organizationQr: 'QR Generator',
  organizationStaff: 'Staff',
  organizationStudents: 'Students',
  organizationUsers: 'Users',
  schoolBus: 'School Bus',
  schoolBusAttendance: 'Bus Attendance',
  schoolBusRouteTracker: 'Route Tracker',
  sms: 'SMS System',
  surveys: 'Surveys',
  surveysAll: 'All Surveys',
  surveysReports: 'Survey Reports',
};
