export default {
  dateOfBirth: 'Date of Birth',
  email: 'Email',
  enrollmentStatus: 'Enrollment Status',
  firstName: 'First Name',
  gender: 'Gender',
  grade: 'Grade',
  lastName: 'Last Name',
  middleName: 'Middle Name',
  notes: 'Notes',
  phoneNumber: 'Phone Number',
  race: 'Race',
  studentId: 'Student Id',
  classification: 'Classification',
};
